"""added column to organization table

Revision ID: 00ee0e4b5edd
Revises: 17c209d6da33
Create Date: 2024-11-07 01:04:33.727748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ee0e4b5edd'
down_revision = '17c209d6da33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('application_date')

    # ### end Alembic commands ###
